job('create-maven-job-via-dsl'){
  description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
  scm{
    git('https://github.com/haseebahmedsyed/Jenkins_Upgradev3.git','master')
  }
  triggers{
    smc('* * * * *')
  }
  steps{
    maven('clean package','maven-samples/single-module/pom.xml')
  }
  publishers{
    archiveArtifacts '**/*.jar'
  }
}
