pipeline{
	agent any
	tools{
		maven 'maven'
	}
	stages{
		stage('Build Application'){
			steps{
				sh 'mvn -f java-tomcat-sample/pom.xml clean package'
			}
			post{
				success{
					echo "Archieving the artifacts.."
					archiveArtifacts artifacts: '**/*.war'
				}
			}
		}
	}
}
