pipeline {
    agent any
	tools{
		maven 'maven'
	}
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
		    script{
	    	echo "Deploying..."
                build job: 'DEPLOY_TO_STAGING_ENV_CODE_DSL', wait: true
			    }
            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'DEPLOY_TO_PRODUCTION_ENV_CODE_DSL', wait: true
            }
        }
    }
}
