pipeline {
    agent any
	tools{
		maven 'maven'
	}
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
		    script{
	    	echo "Deploying..."
                build job: 'Deploy_To_Staging', wait: true
			    }
            }
        }
    }
}
