pipeline {
    agent any
	tools{
		maven 'maven'
	}
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample-docker-Copy/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t haseeb38/sample-tomcat:0.0.1.RELEASE ./java-tomcat-sample-docker - Copy'
            }
        }
    }
}
